<?php

/**
 * @file
 * Module file for sms gateway.
 */

/**
 * Implements hook_help().
 */
function sms_gateway_help($path, $arg) {
  global $base_url;
  global $base_path;
  global $user;

  $uid = $user->uid;
  $config_path = 'user/' . $uid . '/sms-gateway/config';
  $config_url = $base_url . $base_path . $config_path;

  switch ($path) {
    case 'admin/help#sms_gateway':
      $output = '';
      $output .= '<p>' . t('The sms gateway module provides a drupal web interface for your sms transactions on your mobile phone with the use of the services provided by smsgateway.me.') . '</p>';
      $output .= '<p>' . t('This includes per user configuration, sending messages, retrieving messages, managing contacts, group messaging, bulk messaging, and other things you can do with sms in your mobile phone.') . '</p>';
      $output .= '<p>' . t('The maintainers of the this module are not in any way affiliated with smsgateway.me.') . '</p>';
      $output .= '<h2>' . t('Installation') . '</h2>';
      $output .= '<ul>';
      $output .= '<li>' . t('Create account in <a href="@url" target="_blank">@url</a>.', array('@url' => 'https://smsgateway.me/')) . '</li>';
      $output .= '<li>' . t('Download and install <b>@name</b> on your mobile phone and sign-in to your account.', array('@name' => 'SMS Gateway Me')) . '</li>';
      $output .= '<li>' . t('Install and enable <b>@name</b> module into your drupal website.', array('@name' => 'SMS Gateway')) . '</li>';
      $output .= '<li>' . t('Set username (your @account email) and password <a href="@config_url" target="_blank">@config_path</a>',
        array(
          '@account' => 'smsgateway.me',
          '@config_path' => $config_path,
          '@config_url' => $config_url,
        )) . '</li>';
      $output .= '</ul>';
      return $output;
  }
}
