<?php

/**
 * @file
 * Page callbacks for manage contact.
 */

/**
 * Menu callback; displays sms gateway contact list page.
 */
function sms_gateway_contact_list_page() {
  return 'Contacts list page.';
}

/**
 * Menu callback; displays sms gateway contact detail page.
 */
function sms_gateway_contact_detail_page() {
  return 'Contact detail page.';
}

/**
 * Menu callback; displays sms gateway contact edit page.
 */
function sms_gateway_contact_edit_page() {
  return 'Contact edit page.';
}

/**
 * Menu callback; displays sms gateway contact delete page.
 */
function sms_gateway_contact_delete_page() {
  return 'Contact delete page.';
}

/**
 * Menu callback; displays sms gateway contact add page.
 */
function sms_gateway_contact_add_page() {
  return 'Contact add page.';
}
